General:
  N: 4
  D: 4.5
Vertices:
  V1: 0
  V2: 1
  V3: 0
  V4: 2
Edges:
  E1:
    - V1
    - V2
    - 1
  E2:
    - V3
    - V4
    - 1
  E3:
    - V2
    - V3
    - 1
  E4:
    - V1
    - V3
    - 4
  E5:
    - V2
    - V4
    - 5