
General:
  N: 6
  D: 40
Vertices:
  V1: 6
  V2: 0
  V3: 2
  V4: 0
  V5: 7
  V6: 1
Edges:
  E1:
    - V1
    - V2
    - 10
  E2:
    - V2
    - V3
    - 100
  E3:
    - V3
    - V6
    - 1
  E4:
    - V2
    - V4
    - 3
  E5:
    - V4
    - V5
    - 2
  E6:
    - V2
    - V5
    - 1
